theme:
  - cosmo

project:
  type: book
  output-dir: docs

book:
  title: "Iowa State University Department of Statistics Graduate Handbook"

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/isustatistics/graduate_handbook
  repo-branch: main
  chapters:
    - index.qmd

    - part: "Department"
      chapters:
        - department/people.qmd
        - department/snedecor.qmd
    - part: "Academics"
      chapters: 
        - academics/overview.qmd
        - academics/degrees.qmd
        - academics/courses.qmd
        - academics/research.qmd
        - academics/skills.qmd
        - academics/progress.qmd
        - academics/expectations.qmd
    # - part: "Life"
      # chapters:
      #   - life/housing.qmd
    - part: "Appendix"
      chapters:
        - appendix/abbreviations.qmd
        - appendix/changes.qmd

execute:
  freeze: auto