# Degrees

The Department of Statistics at Iowa State University provides the following
graduate degrees:

- Doctor of Philosophy (PhD)
- Master of Science (MS)
- Master of Applied Statistics (MAS) (coming Fall 2025)
- Co-Major Doctor of Philosophy (Co-Major PhD)

The department also confers two graduate minors for students pursuing a 
graduate degree in another department:

- PhD Minor
- MS Minor


## Doctor of Philosophy (PhD)

### Learning Goals

1. Demonstrate comprehensive understanding of advanced statistical methods and theory, including probability, mathematical statistics, and the construction of probability-based models for complex data structures. 
1. Demonstrate the ability to formulate statistical questions on the basis of objectives in substantive scientific investigations, and the ability to compute the quantities needed to bring statistical theory and methods to bear on those questions. 
1. Conduct original research into one or more specific areas of statistical science that is of sufficient depth to merit publication in a statistical or scientific journal. 
1. Demonstrate understanding of the scholarly literature in the area of dissertation research. 
1. Demonstrate the ability to communicate research results to scientists and other researchers in both written and oral formats. 

### Prerequisites

**Multivariable calculus** (at least three semesters of calculus in the U.S. system) 
and **linear algebra** are required background courses. 
Applicants are also encouraged to complete a Real Analysis 
(sometimes called Analysis or Advanced Calculus) course.

### Requirements

The MS degree requires 72 credits including 27 credits in required courses,
at least 18 credits of dissertation research (STAT 6990), 
and at least 15 credits from STAT elective courses including at least three
courses at the 6000 level.
In addition to completing the required course credits, 
the student must pass a written qualifying exam. 
During the final semester of study, 
the student will submit their dissertation to their Academic Plan Committee (APC),
present a public seminar of their work, 
and hold a defense of their dissertation research with their APC.

### Required Courses

The following are the required courses organized by semester.

- Fall Year 1
    - STAT 5000 (4 cr) Statistical Methods I 
    - STAT 5420 (4 cr) Theory of Probability and Statistics I 
    - STAT 5790 (1 cr) An Introduction to R 
- Spring Year 1
    - STAT 5100 (3 cr) Statistical Methods II 
    - STAT 5430 (3 cr) Theory of Probability and Statistics II
- Fall Year 2
    - STAT 5200 (3 cr) Statistical Methods III 
    - STAT 6410 (3 cr) Foundations of Probability Theory
- Spring Year 2
    - STAT 6010 (3 cr) Advanced Statistical Methods
    - STAT 6420 (3 cr) Advanced Probability Theory
    
Dissertation research and elective courses can be taken at any time during
the program.

For student's enrolling in the PhD program who have already obtained an
appropriate Master's Degree in Statistics, 
they may want to receive credit for courses already taken during that degree
in lieu of the required courses listed above. 
The student should obtain syllabi from the courses taken and work with the
Director of Graduate Education (DOGE) to transfer those credits.
 

## Master of Science (MS)

Some students enter our program with the intent of obtaining a Master of Science (MS) degree and then entering the job market. 
Students with a bachelor’s degree who enter the program with the desire to complete the degree of Doctor of Philosophy (PhD) often complete the MS degree first, 
since all MS core courses are also required for the PhD. 
All students seeking the MS degree must complete the same set of core requirements. 

### Prerequisites

**Multivariable calculus** (at least three semesters of calculus in the U.S. system) 
and **linear algebra** are required background courses, 
and knowledge of this material is expected of students in the MS program. 
Applicants should have completed these or equivalent courses prior to application for admission. 

### Requirements

The MS degree requires 34 credits including 18 credits in required courses,
2-4 credits of creative component research, and the remaining credits 
elective STAT courses at the 5000- or 6000-level.
In addition to completing the required course credits, 
the student must pass a written exam. 
During or after the final semester of course work, 
students take an oral exam on work completed for the creative component (a capstone project). This is the *Final Examination* mentioned in the Graduate Catalog. 

### Required Courses

The following are the required courses organized by semester as well as the
typical timing for elective courses.

- Fall Year 1
    - STAT 5000 (4 cr) Statistical Methods I 
    - STAT 5420 (4 cr) Theory of Probability and Statistics I 
    - STAT 5790 (1 cr) An Introduction to R 
- Spring Year 1
    - STAT 5100 (3 cr) Statistical Methods II 
    - STAT 5430 (3 cr) Theory of Probability and Statistics II 
    - STAT Elective (3 cr) 
- Fall Year 2
    - STAT 5200 (3 cr) Statistical Methods III 
    - STAT Electives (3-6 cr) 
- Spring Year 2
    - STAT Electives (3-9 cr) 
    - STAT 5990 (2-4 cr) Creative Component Research
 

## Master of Applied Statistics (MAS) (coming Fall 2025)

More details about this degree are forthcoming. 
For now, please see the details on the 
[MAS page of the department website](https://www.stat.iastate.edu/master-applied-statistics-mas).

## Co-Major Doctor of Philosophy (Co-Major PhD)

A Co-Major PhD 
Co-majors have been pursued with agronomy, animal science, botany, computer science, economics, education, engineering, entomology, genetics, mathematics, meteorology, psychology and sociology. Since the balance of methodological and theoretical statistics required in a discipline varies by program, we offer two tracks for those seeking a Co-Major PhD degree. The Department of Statistics requirements are outlined below. (The requirements of the other department are determined by that department.) 

Track 1 - Applied 

The student must take the Master’s core (STAT 5000, 5100, 5200, 5790, 5420 and 5430) plus STAT 6010.  The program must also include at least three additional 5000- or 6000-level courses in Statistics. The student must also pass a written qualifying exam.
The dissertation must advance the knowledge in at least one of the two disciplines. 

Track 2 - Theory 

The student must take the Master’s core (STAT 5000, 5100, 5200, 5790, 5420 and 5430) plus STAT 6410 and 6420. The program must also include at least three additional 5000- or 6000-level courses in Statistics. The student must also pass a written qualifying exam.
The dissertation must advance the knowledge in at least one of the two disciplines. 

## PhD Minor

The Statistics PhD Minor is for PhD students in other disciplines who are 
interested in obtaining a minor in Statistics. 

### Requirements 

- Complete a minimum of 4 Statistics courses, including STAT 5870, 5880, and at least two elective STAT courses (of at least 3 credits each) at the 5000 level or higher. 
- Receive at least a B grade in both STAT 5870 and 5880, and a grade point average for the four courses of at least 3.33 (B+). 
- Include at least one Department of Statistics faculty member as a minor representative on your Academic Plan Committee.

Note: 
STAT 5000 can be substituted for STAT 5870, 
but only one of the two courses can be used for Minor credit. 
STAT 5420 and STAT 5430 can substitute for STAT 5880,
but only one of the two courses can be used for Minor credit.
If you take 5420 and 5430 instead of 5880, 
you will still need two electives (for a total of 5 courses) to complete the Minor requirement.  


## MS Minor

The Statistics MS Minor is for MS students in other disciplines who are 
interested in obtaining a minor in Statistics. 

### Requirements 

- Complete a minimum of 3 Statistics courses, including STAT 5870, 5880, and at least one elective STAT course (of at least 3 credits each) at the 5000 level or higher. 
- Receive at least a B grade in both STAT 5870 and 5880, and a grade point average for the four courses of at least 3.33 (B+). 
- Include at least one Department of Statistics faculty member as a minor representative on your Academic Plan Committee.

Note: 
STAT 5000 can be substituted for STAT 5870, 
but only one of the two courses can be used for Minor credit. 
STAT 5420 and STAT 5430 can substitute for STAT 5880,
but only one of the two courses can be used for Minor credit.
If you take 5420 and 5430 instead of 5880, 
you will still need two electives (for a total of 4 courses) to complete the Minor requirement.  

