# Expectations

In addition to the formal [progress checks](progress.html),
the department has expectations about how you interact. 

## Attend class

You should plan on attending all classes.
Arrive early and be prepared for class to start on time. 
If you cannot attend a class, 
send the instructor an email indicating that you cannot attend a brief explanation
of why. 
After the class, obtain notes from a classmate. 

## Complete readings

Read assigned material. 

## Complete homework

Complete all homework on time. 
Even when the semester is hectic, 
you need to develop the time management skills to balance it all. 
Typically this means getting homework completed early.

If provided, review homework solutions to see how the instructor would have
solved a given problem. 

## Study

Plan to review content within 24 hours of it being presented to maximize 
retention. 
Be prepared for exams. 

## Respond to email

Through the semester, various people (including course instructors) will email
you. 
Make sure to read your email on a daily basis and respond accordingly. 

## Check Canvas

Canvas is the course management system at ISU. 
You should plan to check Canvas on a daily basis. 


