# Program Overview

The Statistics Department is part of the College of Liberal Arts & Sciences (LAS) and, nominally, the College of Agriculture & Life Studies (CALS).

The graduate program in the Department of Statistics is administered by a Department Chair, Associate Chair, and DOGE (Director of Graduate Education). Support staff include a Graduate Student Support Services Specialist, Administrative Specialists, and Undergraduate Student Support Services Specialist. All are available to help students with any questions or concerns they may have.

Students are admitted to the program as a STAT major through LAS. Some interdisciplinary programs may also have students select STAT as their home department, depending on where their major professor is housed, even if they are not a Statistics major. While many students admitted directly to the PhD program with only a Bachelor’s, those students may choose to pursue an MS degree in addition to the PhD. Students who are admitted to the MS program but are interested in also pursuing the PhD in Statistics are free to consult with the DOGE to review their options and discuss any requirements that may need to be met before becoming eligible.
