# People

The Department of Statistics Website provides updated information on department
personnel including

- [Faculty](https://www.stat.iastate.edu/people/faculty)
- [Staff](https://www.stat.iastate.edu/people/staff)
- [Graduate Students](https://www.stat.iastate.edu/people/graduate-students)

This page intends to provide you with information about the roles in the 
department and how they are relevant to you. 

## Graduate Student Services Specialist (GSSS)

The GSSS will serve as the primary administrative contact for students.  
This position assists students in navigating their time at ISU, 
answer questions, or direct to student resources.  
The GSSS also facilitates program administration and will coordinate with other 
university officers on matters related to academic programs, assistantships, 
fellowships, etc.  

Appointment Hours: M-F 9:30 - 11:30 AM & 2:00 - 4:00 PM 



## Director of Graduate Recruiting and Admissions

The Director of Graduate Recruiting and Admissions admitted you to the university
and provided a main point of contact, in addition to the GSSS, 
before your arrival on campus. 


## Director of Graduate Education (DOGE)

The Statistics DOGE is responsible for acting as the temporary advisor for all 
incoming graduate students until a student has a designated major professor.  
The DOGE will coordinate and oversee administration of graduate degree programs 
and ensures that graduate students meet the academic requirements of the program. Responsibilities include approval of POSCAPC forms, academic plans, and graduation applications. The DOGE ensures that graduate examinations are properly conducted.  
Additional duties, may include: mediating disputes between graduate students 
and advisors, and leading discussions of issues important to the major.

## Department Chair

The Department Chair oversees everyone in the Department of Statistics. 



